# Generated by Django 4.2.3 on 2023-08-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelos", "0002_alter_project_options_project_precio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="precio",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
