# Generated by Django 4.2.3 on 2023-08-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelos", "0003_alter_project_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(verbose_name="Dato6"),
        ),
    ]
