# Generated by Django 4.2.3 on 2023-08-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelos", "0004_alter_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="alimentacion",
            field=models.TextField(
                default="Valor predeterminado",
                max_length=200,
                verbose_name="Alimentacion",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="caja_de_cambios",
            field=models.TextField(
                default="Valor predeterminado",
                max_length=200,
                verbose_name="Caja de Cambios",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="cilindraje",
            field=models.TextField(
                default="Valor predeterminado", verbose_name="Cilindraje"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="motor",
            field=models.TextField(
                default="Valor predeterminado", max_length=200, verbose_name="Motor"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="par_maximo",
            field=models.TextField(
                default="Valor predeterminado", verbose_name="Par Maximo"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="potencia",
            field=models.TextField(
                default="Valor predeterminado", verbose_name="Potencia"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="situacion",
            field=models.TextField(
                default="Valor predeterminado", verbose_name="Sitacion"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="traccion",
            field=models.TextField(
                default="Valor predeterminado", verbose_name="Traccion"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="valvulas",
            field=models.TextField(
                default="Valor predeterminado", verbose_name="Valvulas"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(verbose_name="Descripcion"),
        ),
    ]
