# Generated by Django 4.2.3 on 2023-08-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelos", "0005_project_alimentacion_project_caja_de_cambios_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="precio",
            field=models.TextField(
                default="Valor predeterminado", max_length=5, verbose_name="Precio"
            ),
        ),
    ]
