# Generated by Django 4.2.1 on 2023-08-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0006_alter_project_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='precio',
            field=models.TextField(default='Valor predeterminado', max_length=50, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='situacion',
            field=models.TextField(default='Valor predeterminado', verbose_name='Situacion'),
        ),
    ]
